### ISSUE TITLE
서버 내 Python 영상처리 모듈 실행

### ISSUE THREAD

**Issue by marching0531** [kookmin-sw/2018-cap1-2#1]
Java 서버 내부에서 Python 영상처리 모듈 실행

**Comment by shinjong93** [comment]
파이썬 / 인터프리터 개별로 데몬을 돌면서 서로 다른 폴더를 감시해서 해당 폴더에 파일이 추가되면 자동으로 동작을 실행하게 하면 안될까?

영상처리 모듈을 위한 파이썬 라이브러리 해결 방안은 아직 찾는중...

**Comment by marching0531** [comment]
#10 으로 issue 수정
