### ISSUE TITLE
AWS 서버 신청할 것

### ISSUE THREAD

**Issue by occidere** [kookmin-sw/2018-cap1-2#11]
# AWS 서버 신청할 것
* **(필수) 개발서버**
* (선택) 운영서버

## Required Specifications
* OS: **Ubuntu 16.04+** or **CentOS 7.3+**
* RAM: 16GB ~ 8GB
* Storage: HDD 100GB+
* Network: 1Gbps ~ 100Mbps
* GPU(Optional)

**Comment by shinjong93** [comment]
일단 신청은 했고, 서버 발급 받은 이후에 과사에 문의해서 좀 더 정확하게 어떻게 해야하는 지 알아볼게.

**Comment by marching0531** [comment]
#33 과 통합
