### ISSUE TITLE
각자 개발할 브랜치 생성하며 개발하기

### ISSUE THREAD

**Issue by shinjong93** [kookmin-sw/2018-cap1-2#14]
<이름>_<브랜치 번호>의 형식으로 이름 짓고 완성되면 마스터에서 합치는 방식으로 합시다.

성적에 반영하기 위해 작업이 완료된 브랜치는 닫지 말고 유지해야함.

가능한 현재 해결해야하는 목표를 이슈에 설정하고 그 번호를 따라주기를 바랍니다.

예시로 나는 영상처리 3번 이슈 해결 예정이므로 브랜치는 IP_3을 사용할 예정입니다.

**Comment by shinjong93** [comment]
브랜치 만들라는 데 안만들고 계속할 수도 없으니...

**Comment by occidere** [comment]
확인완료

**Comment by occidere** [comment]
브랜치 번호 부분이 어떤 의미인지?
이슈 번호 얘기하는거?

**Comment by marching0531** [comment]
잘 실행하고 있으므로 이슈 정리를 위해 닫겠습니다
