### ISSUE TITLE
Server-Client 통신 시 발생 가능한 경우의 수 분석

### ISSUE THREAD

**Issue by InjeongChoii** [kookmin-sw/2018-cap1-2#15]
소켓 통신 시 발생할 수 있는 경우의 수 분석 &
경우의 수에 대응하는 response code 매칭 작업 필요.

**Comment by InjeongChoii** [comment]
소켓 통신에서 response code 를 데이터랑 분리시켜 전송하는게 가능?

**Comment by occidere** [comment]
웹 통신 하는게 아니라서 response code가 따로 없긴 한데,
우리 프로젝트만의 프로토콜을 만들면 가능하긴 할 듯

**Comment by occidere** [comment]
아니면 `시스템에러` 처리는 SocketException 나는거 받아 처리하면 될 듯 하고,
그 이외 `로지컬에러` 부분은 서버에서 빨간줄 하이라이팅 할 부분 정보를 같이 넘겨주는 식으로 처리하면 될 듯

**Comment by InjeongChoii** [comment]
로지컬에러 발생이랑 성공도 액티비티를 다르게 넘겨줘야하니까
프로토콜 만들어서 앞쪽에 붙여주는게 편리해보이는데
어떻게 생각?

**Comment by occidere** [comment]
ㅇㅋ 그렇게 하는게 나을듯

**Comment by occidere** [comment]
관련 이슈 오픈 #16

**Comment by occidere** [comment]
## 발생 가능한 상태
1. Success: 모든 작업이 성공적으로 처리됨
2. Logical Error: 시스템의 문제는 없으나, 사용자의 코드에 문법적 오류가 있어서 발생하는 에러
3. System Error: 통신, io, 영상처리 등의 Logical Error를 제외한 나머지 에러

**Comment by occidere** [comment]
더 이상 파악된 상태가 없으므로 닫음.
추후 다른 경우의 수 발생 확인 시 새로 이슈를 열을 것.
