### ISSUE TITLE
각 모듈마다 Travis CI 적용하여 빌드 검사할 것

### ISSUE THREAD

**Issue by occidere** [kookmin-sw/2018-cap1-2#19]
# 각 모듈마다 Travis CI 적용하여 빌드 검사할 것
* 참고: https://travis-ci.org/

**Comment by shinjong93** [comment]
ㅇㅋ 확인해볼게

**Comment by occidere** [comment]
방금 추가하려고 봤더니, kookmin-sw 계정에 권한요청해야되서 일단 해놓음

**Comment by occidere** [comment]
계속 승인을 안해줘서 닫음
