### ISSUE TITLE
브랜치 관련 상세 설명

### ISSUE THREAD

**Issue by shinjong93** [kookmin-sw/2018-cap1-2#20]
<이름>_<번호>의 형식으로 통일하고자 하며, 번호는 다른 사람들과 반드시 같아야할 필요 없음.

생성하는 브랜치마다 번호를 증가시켜서 한눈에 가장 최근의 브랜치가 어느 브랜치인지만 확인 할 수 있으면 됨.

예를 들어 IP_<번호>로 영상처리 관련 브랜치를 생성하고 있는데, 이슈 번호에 따라 <번호> 부분이 변경되고 있고 현재 3번째 브랜치에서 작업중. 숫자가 가장 큰 브랜치가 최근 작업하고 있는 브랜치.

**Comment by shinjong93** [comment]
아, 브랜치에서 작업 다 끝나고 병합 완료 후에도 브랜치 닫지 말것.

**Comment by occidere** [comment]
나 같은 경우엔 개별적으로 이슈 번호를 안붙여서 그냥 전체 이슈 번호 (#19) 붙은거 쓰도록 할게

**Comment by marching0531** [comment]
#14 와 같은 이유로 닫겠습니다
