### ISSUE TITLE
영상처리 - 4 윤곽선 개선 

### ISSUE THREAD

**Issue by shinjong93** [kookmin-sw/2018-cap1-2#24]
i , =  등 과 같이 하나의 글자이지만 2개의 부분으로 떨어져있는 경우 윤곽선이 2개로 잡히는 문제가 발생함.

이를 해결하기 위한 코드의 개선이 필요.

**Comment by occidere** [comment]
좌->우 & 상 -> 하 정렬 관련
http://answers.opencv.org/question/31515/sorting-contours-from-left-to-right-and-top-to-bottom/
