### ISSUE TITLE
텍스트 자동완성 기능에 대하여 조사

### ISSUE THREAD

**Issue by shinjong93** [kookmin-sw/2018-cap1-2#35]
자동 완성 기능을 조사, 프로젝트에 활용 가능성이 있는 지 알아봐주기 바랍니다.

**Comment by occidere** [comment]
# 자동완성 기능 여부
* 영상처리를 통해 추출된 raw text에서, 앞에부터 글자를 읽어들이며 자동완성을 하는것으로 이해함
* 자동완성 자체가 유사도 기반으로 하는 것이 대부분이라 영상처리 아웃풋의 정확도가 불분명한 상태에서는 적절하지 않음
  - 예를들어 f0r를 for로 자동완성을 매칭시키는 것은 말이 되나, System.out.println("for me") 등의 극단적인 경우엔 적용되기 어렵고, 이외의 예외도 많음
  - 유사도 알고리즘 없이 완전 일치시에만 적용한다고 하면 큰 의미가 없음
* 또한 맨 아워가 많이 요구되는 작업인 만큼 쉽사리 인력을 돌리기 힘듦
* 따라서 영상처리에서 원문 텍스트를 그대로 뽑아내는 배치를 생성하는 것이 더욱 효율적이라 판단됨

**Comment by shinjong93** [comment]
교수님 왈,
"답변이 매우 부정적입니다. 가능한 방법을 찾을 수 있도록 노력을 해야지 안되는 방법만 나열해서는 과제를 해결 할 수 없습니다. 위의 내용은 내가 지적한 사항도 제대로 이해하지 못하였을 뿐만 아니라, 문제를 해결하기 위한 노력도 하나도 보이지 않아 매우 실망스럽습니다."

**Comment by marching0531** [comment]
[Google Docs Link](https://docs.google.com/document/d/1nT4IuLlFySWjdF7Nzi6r69DVYv5uSjffuTSRHxLCvHM/edit?usp=sharing)
관련 조사 및 Interpreter 보충 설명 파일입니다
