### ISSUE TITLE
발표 준비 및 대본 녹음

### ISSUE THREAD

**Issue by shinjong93** [kookmin-sw/2018-cap1-2#5]
200초 내외로 발표 준비 및 대본 녹음 완료해야함.

현재 측정으로는 220초 언저리에서 완료되고 있으니 녹음을 들어보고 피드백 바람.

**Comment by occidere** [comment]
확인완료

**Comment by marching0531** [comment]
스크립트가 너무 많아서 급한 느낌이 나는데
내용을 조금은  쳐내도 되지 않을까
